=== miguelnunezcaro/LENGUAJE-DE-MARCAS/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS/ExamenXML/ejer1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT supermercado (articulo+)>
<!ELEMENT articulo (descripcion, marca, medida, seccion, oferta* , perecedero?)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT medida (#PCDATA)>
<!ELEMENT seccion (#PCDATA)>
<!ELEMENT oferta (#PCDATA)>
<!ELEMENT perecedero (caducidad)>
<!ELEMENT caducidad (#PCDATA)>
<!ATTLIST articulo n_art CDATA #REQUIRED>
<!ATTLIST articulo cantidad CDATA #IMPLIED>
<!ATTLIST marca tipo CDATA #IMPLIED>
<!ATTLIST medida unidad CDATA #IMPLIED>

=== miguelnunezcaro/LENGUAJE-DE-MARCAS/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS/ExamenXML/ejer1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE supermercado SYSTEM "ejer1.dtd">
<supermercado>
<articulo n_art="articulo1" cantidad="300">
<descripcion>Yogurt</descripcion>
<marca tipo="nacional">Danone</marca>
<medida unidad="Sistema Internacional">200 ml</medida>
<seccion>Lacteos</seccion>
</articulo>
<articulo n_art="articulo2">
<descripcion>Queso fresco</descripcion>
<marca tipo="nacional">Burgo de Arias</marca>
<medida>250 gr</medida>
<seccion>Lacteos</seccion>
<oferta>Lote descuento</oferta>
<perecedero>
<caducidad>febrero de 2022</caducidad>
</perecedero>
</articulo>
</supermercado>
