<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos [
<!ELEMENT productos (producto)*>
<!ELEMENT producto (identificacion, nombre)>
<!ELEMENT identificacion (#PCDATA | codigo | id)*>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
]>
<productos>
<producto>
    <identificacion>
    <codigo>MAR264</codigo>
    </identificacion>
    <nombre>martillo</nombre>
</producto>
<producto>
    <identificacion>
     No hay stock.
    </identificacion>
    <nombre>destornillador</nombre>
</producto>
</productos>