=== miguelnunezcaro/LENGUAJE-DE-MARCAS/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS/CuadernilloAct3/Act5.dtd
<!ELEMENT disco (titulo, interprete, numero_pista)>
<!ELEMENT interprete (nombre, apellidos, rol)>
<!ELEMENT numero_pista (nombre_cancion, duracion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT nombre_cancion (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

=== miguelnunezcaro/LENGUAJE-DE-MARCAS/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS/CuadernilloAct3/Act5e.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE disco SYSTEM "Act5.dtd">
<disco>
    <titulo>

    </titulo>
    <interprete>
        <nombre></nombre>
        <apellidos></apellidos>
        <rol> </rol>
    </interprete>
    <numero_pista>
        <nombre_cancion> </nombre_cancion>
        <duracion> </duracion>
    </numero_pista>
</disco>
